// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/patrol/v1/patrol.proto

package patrolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SloName       string                 `protobuf:"bytes,1,opt,name=slo_name,json=sloName,proto3" json:"slo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_patrol_v1_patrol_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusRequest) GetSloName() string {
	if x != nil {
		return x.SloName
	}
	return ""
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SloName         string                 `protobuf:"bytes,1,opt,name=slo_name,json=sloName,proto3" json:"slo_name,omitempty"`
	BurnRate        float64                `protobuf:"fixed64,2,opt,name=burn_rate,json=burnRate,proto3" json:"burn_rate,omitempty"`
	BudgetConsumed  float64                `protobuf:"fixed64,3,opt,name=budget_consumed,json=budgetConsumed,proto3" json:"budget_consumed,omitempty"`
	BudgetRemaining float64                `protobuf:"fixed64,4,opt,name=budget_remaining,json=budgetRemaining,proto3" json:"budget_remaining,omitempty"`
	ErrorRate       float64                `protobuf:"fixed64,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_patrol_v1_patrol_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetSloName() string {
	if x != nil {
		return x.SloName
	}
	return ""
}

func (x *GetStatusResponse) GetBurnRate() float64 {
	if x != nil {
		return x.BurnRate
	}
	return 0
}

func (x *GetStatusResponse) GetBudgetConsumed() float64 {
	if x != nil {
		return x.BudgetConsumed
	}
	return 0
}

func (x *GetStatusResponse) GetBudgetRemaining() float64 {
	if x != nil {
		return x.BudgetRemaining
	}
	return 0
}

func (x *GetStatusResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *GetStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetGateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SloName       string                 `protobuf:"bytes,1,opt,name=slo_name,json=sloName,proto3" json:"slo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGateRequest) Reset() {
	*x = GetGateRequest{}
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateRequest) ProtoMessage() {}

func (x *GetGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateRequest.ProtoReflect.Descriptor instead.
func (*GetGateRequest) Descriptor() ([]byte, []int) {
	return file_proto_patrol_v1_patrol_proto_rawDescGZIP(), []int{2}
}

func (x *GetGateRequest) GetSloName() string {
	if x != nil {
		return x.SloName
	}
	return ""
}

type GetGateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGateResponse) Reset() {
	*x = GetGateResponse{}
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateResponse) ProtoMessage() {}

func (x *GetGateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_patrol_v1_patrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateResponse.ProtoReflect.Descriptor instead.
func (*GetGateResponse) Descriptor() ([]byte, []int) {
	return file_proto_patrol_v1_patrol_proto_rawDescGZIP(), []int{3}
}

func (x *GetGateResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *GetGateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_patrol_v1_patrol_proto protoreflect.FileDescriptor

const file_proto_patrol_v1_patrol_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/patrol/v1/patrol.proto\x12\tpatrol.v1\"-\n" +
	"\x10GetStatusRequest\x12\x19\n" +
	"\bslo_name\x18\x01 \x01(\tR\asloName\"\xdd\x01\n" +
	"\x11GetStatusResponse\x12\x19\n" +
	"\bslo_name\x18\x01 \x01(\tR\asloName\x12\x1b\n" +
	"\tburn_rate\x18\x02 \x01(\x01R\bburnRate\x12'\n" +
	"\x0fbudget_consumed\x18\x03 \x01(\x01R\x0ebudgetConsumed\x12)\n" +
	"\x10budget_remaining\x18\x04 \x01(\x01R\x0fbudgetRemaining\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\x01R\terrorRate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"+\n" +
	"\x0eGetGateRequest\x12\x19\n" +
	"\bslo_name\x18\x01 \x01(\tR\asloName\"?\n" +
	"\x0fGetGateResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x99\x01\n" +
	"\rPatrolService\x12F\n" +
	"\tGetStatus\x12\x1b.patrol.v1.GetStatusRequest\x1a\x1c.patrol.v1.GetStatusResponse\x12@\n" +
	"\aGetGate\x12\x19.patrol.v1.GetGateRequest\x1a\x1a.patrol.v1.GetGateResponseB2Z0github.com/renvins/patrol/gen/patrol/v1;patrolv1b\x06proto3"

var (
	file_proto_patrol_v1_patrol_proto_rawDescOnce sync.Once
	file_proto_patrol_v1_patrol_proto_rawDescData []byte
)

func file_proto_patrol_v1_patrol_proto_rawDescGZIP() []byte {
	file_proto_patrol_v1_patrol_proto_rawDescOnce.Do(func() {
		file_proto_patrol_v1_patrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_patrol_v1_patrol_proto_rawDesc), len(file_proto_patrol_v1_patrol_proto_rawDesc)))
	})
	return file_proto_patrol_v1_patrol_proto_rawDescData
}

var file_proto_patrol_v1_patrol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_patrol_v1_patrol_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: patrol.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: patrol.v1.GetStatusResponse
	(*GetGateRequest)(nil),    // 2: patrol.v1.GetGateRequest
	(*GetGateResponse)(nil),   // 3: patrol.v1.GetGateResponse
}
var file_proto_patrol_v1_patrol_proto_depIdxs = []int32{
	0, // 0: patrol.v1.PatrolService.GetStatus:input_type -> patrol.v1.GetStatusRequest
	2, // 1: patrol.v1.PatrolService.GetGate:input_type -> patrol.v1.GetGateRequest
	1, // 2: patrol.v1.PatrolService.GetStatus:output_type -> patrol.v1.GetStatusResponse
	3, // 3: patrol.v1.PatrolService.GetGate:output_type -> patrol.v1.GetGateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_patrol_v1_patrol_proto_init() }
func file_proto_patrol_v1_patrol_proto_init() {
	if File_proto_patrol_v1_patrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_patrol_v1_patrol_proto_rawDesc), len(file_proto_patrol_v1_patrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_patrol_v1_patrol_proto_goTypes,
		DependencyIndexes: file_proto_patrol_v1_patrol_proto_depIdxs,
		MessageInfos:      file_proto_patrol_v1_patrol_proto_msgTypes,
	}.Build()
	File_proto_patrol_v1_patrol_proto = out.File
	file_proto_patrol_v1_patrol_proto_goTypes = nil
	file_proto_patrol_v1_patrol_proto_depIdxs = nil
}
