// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/patrol/v1/patrol.proto

package patrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatrolService_GetStatus_FullMethodName = "/patrol.v1.PatrolService/GetStatus"
	PatrolService_GetGate_FullMethodName   = "/patrol.v1.PatrolService/GetGate"
)

// PatrolServiceClient is the client API for PatrolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatrolServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetGate(ctx context.Context, in *GetGateRequest, opts ...grpc.CallOption) (*GetGateResponse, error)
}

type patrolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatrolServiceClient(cc grpc.ClientConnInterface) PatrolServiceClient {
	return &patrolServiceClient{cc}
}

func (c *patrolServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, PatrolService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) GetGate(ctx context.Context, in *GetGateRequest, opts ...grpc.CallOption) (*GetGateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGateResponse)
	err := c.cc.Invoke(ctx, PatrolService_GetGate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatrolServiceServer is the server API for PatrolService service.
// All implementations must embed UnimplementedPatrolServiceServer
// for forward compatibility.
type PatrolServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetGate(context.Context, *GetGateRequest) (*GetGateResponse, error)
	mustEmbedUnimplementedPatrolServiceServer()
}

// UnimplementedPatrolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatrolServiceServer struct{}

func (UnimplementedPatrolServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPatrolServiceServer) GetGate(context.Context, *GetGateRequest) (*GetGateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGate not implemented")
}
func (UnimplementedPatrolServiceServer) mustEmbedUnimplementedPatrolServiceServer() {}
func (UnimplementedPatrolServiceServer) testEmbeddedByValue()                       {}

// UnsafePatrolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatrolServiceServer will
// result in compilation errors.
type UnsafePatrolServiceServer interface {
	mustEmbedUnimplementedPatrolServiceServer()
}

func RegisterPatrolServiceServer(s grpc.ServiceRegistrar, srv PatrolServiceServer) {
	// If the following call panics, it indicates UnimplementedPatrolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatrolService_ServiceDesc, srv)
}

func _PatrolService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_GetGate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).GetGate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_GetGate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).GetGate(ctx, req.(*GetGateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatrolService_ServiceDesc is the grpc.ServiceDesc for PatrolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatrolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patrol.v1.PatrolService",
	HandlerType: (*PatrolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PatrolService_GetStatus_Handler,
		},
		{
			MethodName: "GetGate",
			Handler:    _PatrolService_GetGate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/patrol/v1/patrol.proto",
}
